---
- name: Reconcile authelia compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ authelia_root }}"
    remove_orphans: true
    state: present
  listen: reconcile authelia

- name: Restart authelia
  community.docker.docker_compose_v2:
    project_src: "{{ authelia_root }}"
    services: [authelia]
    state: restarted
  changed_when: false
  listen: restart authelia
